ServerHost = "localhost"
ServerPort = "8080"
CachePort = "6379"
MongoPort = "27017"
MongoDatabase = "local"
MongoEmployeeCol = "employers"
MongoTeamsCol = "teams"
MySqlPort ="3306"
MySqlUser ="root"
MySqlHost ="127.0.0.1"
MySqlDatabase = "app"
MySqlEmployee = "employers"
MySqlTeams = "teams"
MySqlTeamMem = "teamMembers"